### ISSUE TITLE
UberJAR does not copy files from web in core module if we place files under web/vaadin

### ISSUE THREAD

**Issue by Flaurite** [cuba-platform/cuba-gradle-plugin#118] opened 2019-10-02 13:00 UTC
### Environment
- Platform version: 7.1
- Gradle version: 4.10.1 and 4.10.3
- Operating system: Windows 10

### Description of the bug or enhancement
If we place files under `core/web/VAADIN/some_file` it will not be copied to UberJAR.
- Minimal reproducible example
1. Create application
2. Configure UberJAR task: [documentation](https://doc.cuba-platform.com/manual-7.1/build.gradle_buildUberJar.html)
3. Place some image file to `core/web/VAADIN/your_image.png`
4. Build UberJAR
5. Open it and go to `LIB-INF/app-core/VAADIN`
- Expected behavior
Will see your_image.png
- Actual behavior
No image is copied

**Comment by knstvk** [comment] 2019-10-07 06:47
@Flaurite How do you use files in `core/web/VAADIN`? It's middle tier, why do you need this?

**Comment by Flaurite** [comment] 2019-10-07 06:53
@knstvk Since we started to deploy Sampler as UberJar some images are not deployed to file storage when we launch an application. We decided to copy them form jar to file storage manually from `AppContextInitializedEvent`

**Comment by knstvk** [comment] 2019-10-07 07:53
@Flaurite So the problem is solved?

**Comment by knstvk** [comment] 2019-10-07 08:42
Then I close the issue.

**Closed by knstvk** 2019-10-07 08:42 UTC
Labels: type: bug
